- lineinfile: line="[0:0] -A TCP -p tcp --dport 58846 -j ACCEPT"
               insertbefore="COMMIT"
               dest="/var/lib/machines/deluge/var/lib/ip{{ item }}tables/rules-save"
  register: iptables
  with_items:
  - ""
  - "6"

- machines: name=deluge mode=run
            cmd="/usr/bin/systemctl start ip{{ item }}tables-restore"
  when: iptables|changed
  with_items:
  - ""
  - "6"

- shell: machinectl status deluge | awk '/Address:/{print$2}'
  register: deluge_v4addr
  changed_when: False

- iptables: comment=DELUGE
            ip_version=ipv4
            table=nat
            chain=PREROUTING
            protocol=tcp
            destination_port=58846
            to_destination="{{ deluge_v4addr.stdout }}:58846"
            jump=DNAT
            #action=insert
