- include: container.yml
- include: portage.yml

- name: start deluge container
  machines: name=deluge ensure=running
  register: start

- pause: seconds=20
  when: start|changed

- machines: name=deluge mode=pkg pkg={{item}}
  with_items:
  - deluge

- file: state=link src=/usr/lib/systemd/system/deluged.service
        dest=/var/lib/machines/deluge/etc/systemd/system/multi-user.target.wants/deluged.service
        force=yes
  register: deluge_service_link

- include: user.yml
- include: volume.yml

- machines: name=deluge mode=run
            cmd="/usr/bin/systemctl restart deluged"
  when: deluge_service_link|changed or deluge_create|changed

- include: iptables.yml

- set_fact:
    deluge_user: deluge
    deluge_password: "{{ lookup('password', 'credentials/deluge/' + inventory_hostname + '/password chars=ascii_letters,digits') }}"

- lineinfile: line="{{ deluge_user }}:{{ deluge_password }}:5"
              dest=/srv/volumes/deluge/.config/deluge/auth
