- shell: "awk -F: '/deluge/{print$3}' /var/lib/machines/deluge/etc/passwd | head -1"
  register: deluge_owner
  changed_when: False

- shell: "awk -F: '/deluge/{print$4}' /var/lib/machines/deluge/etc/passwd | head -1"
  register: deluge_group
  changed_when: False

- file: state=directory
        dest=/srv/volumes/deluge
        mode=0755
        owner={{ deluge_owner.stdout }}
        group={{ deluge_group.stdout }}
  register: deluge_dir

- file: state=directory
        dest=/srv/volumes/deluge
        owner={{ deluge_owner.stdout }}
        group={{ deluge_group.stdout }}
        recurse=yes
  when: deluge_dir|changed
