#!/bin/bash

hosts=$1
shift

playbook=$(mktemp -p .)
for host in $@; do
	echo -e "- hosts: $hosts\n  roles:" >> $playbook
	echo "  - keys" >> $playbook
	ansible-playbook -v -e container=$host $playbook
done
rm "$playbook"
