- name: start {{ container }} container
  machines: name={{ container }} ensure=running
  register: "container_start"

- name: await container startup
  pause: seconds=10
  when: container_start|changed
