- include: preamble.yml

- file: path=/etc/systemd/{{ item }} state=directory
  with_items:
  - nspawn
  - network

- name: gshis.nspawn
  copy: src=files/gshis.nspawn
        dest=/etc/systemd/nspawn/gshis.nspawn

- name: br0.netdev
  copy: src=files/br0.netdev
        dest=/etc/systemd/network/br0.netdev
  register: br0

- name: update networkd
  shell: systemctl restart systemd-networkd
  when: br0|changed
