- name: clone plex container
  machines: name=plex source=gshis-{{ gshis_describe.stdout }}-systemd ensure=present
  register: plex_create

- name: machineid
  shell: systemd-machine-id-setup --root /var/lib/machines/plex
  args:
    creates: /var/lib/machines/plex/etc/machine-id

- name: plex nspawn
  copy: src=files/plex.nspawn dest=/etc/systemd/nspawn/plex.nspawn

- name: mediacache
  btrfs: state=present name=/srv/mediacache

- name: plex data volume
  btrfs: state=present name=/srv/volumes/plex

