- include: tasks/create.yml

- name: plex nspawn
  copy: src=files/plex.nspawn dest=/etc/systemd/nspawn/plex.nspawn

- name: mediacache
  btrfs: state=present name=/srv/mediacache
  when: ansible_hostname != "azolla"

- name: plex data volume
  btrfs: state=present name=/srv/volumes/plex

