- include: container.yml
- include: portage.yml

# Before starting container, modify default firewall to allow port 32400
- lineinfile: line="[0:0] -A TCP -p tcp --dport 32400 -j ACCEPT"
              insertbefore="COMMIT"
              dest="/var/lib/machines/plex/var/lib/ip{{ item }}tables/rules-save"
  with_items:
  - ""
  - "6"

- name: start plex container
  machines: name=plex ensure=running
  register: start

- pause: seconds=20
  when: start|changed

# Fix UID/GID of plex volume
- stat: path=/var/lib/machines/plex
  register: plex_root
- file: dest=/srv/volumes/plex
        owner={{ plex_root.stat.uid}} group={{ plex_root.stat.gid }} mode=755
        state=directory

- machines: name=plex mode=pkg pkg={{item}}
  with_items:
  - plex-media-server

- file: state=link src=/etc/systemd/system/plexmediaserver.service
        dest=/var/lib/machines/plex/etc/systemd/system/multi-user.target.wants/plexmediaserver.service
        force=yes
  register: service_link

- include: volume.yml

- machines: name=plex mode=run
            cmd="/usr/bin/systemctl restart plexmediaserver"
  when: service_link|changed or plex_create|changed

- shell: machinectl status plex | awk '/Address:/{print$2}'
  register: plex_v4addr

- iptables: comment=PLEX
            ip_version=ipv4
            table=nat
            chain=PREROUTING
            protocol=tcp
            destination_port=32400
            to_destination="{{ plex_v4addr.stdout }}:32400"
            jump=DNAT
