- name: plex keyword
  lineinfile: name=/var/lib/machines/plex/etc/portage/package.accept_keywords line='media-tv/plex-media-server'

- name: plex license
  lineinfile: name=/var/lib/machines/plex/etc/portage/package.license line='media-tv/plex-media-server PMS-License' create=yes

- name: create repos.conf directory
  file: state=directory name=/var/lib/machines/plex/etc/portage/repos.conf

- name: create portage overlay tld
  file: state=directory name=/var/lib/machines/plex/usr/local/portage

- name: copy megacoffee repo.conf
  copy: src=files/megacoffee.conf dest=/var/lib/machines/plex/etc/portage/repos.conf/megacoffee.conf

- git: dest=/var/lib/machines/plex/usr/local/portage/megacoffee
      repo=https://github.com/theappleman/megacoffee-overlay
      version=plex

